2019-05-23 15:20:35,077 - [create_grafana_dashboards.py:263 - create_service_dashboards() ] - ERROR - Dashboard creation error: Red App Center
Traceback (most recent call last):
  File "create_grafana_dashboards.py", line 260, in create_service_dashboards
    create_single_dashboard(dash_text, service.name, org_id, dash_uid, folder_name)
  File "create_grafana_dashboards.py", line 205, in create_single_dashboard
    resp = dashboards_for_organization.create_dashboard(str(dash_uid), json.loads(request_data))
  File "/opt/aed/shp/lib/grafana/dashboards.py", line 40, in create_dashboard
    id = self.helper.api_post_with_data('dashboards/db', json)
  File "/Library/Python/2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Library/Python/2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/Library/Python/2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Library/Python/2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/aed/shp/lib/grafana/helper.py", line 67, in api_post_with_data
    raise IOError("Error in api_post_with_data: " + function + " - " + resp.text)
IOError: Error in api_post_with_data: dashboards/db - {"message":"Failed to save dashboard"}
2019-05-23 15:20:47,324 - [create_grafana_dashboards.py:263 - create_service_dashboards() ] - ERROR - Dashboard creation error: eHotels
Traceback (most recent call last):
  File "create_grafana_dashboards.py", line 260, in create_service_dashboards
    create_single_dashboard(dash_text, service.name, org_id, dash_uid, folder_name)
  File "create_grafana_dashboards.py", line 205, in create_single_dashboard
    resp = dashboards_for_organization.create_dashboard(str(dash_uid), json.loads(request_data))
  File "/opt/aed/shp/lib/grafana/dashboards.py", line 40, in create_dashboard
    id = self.helper.api_post_with_data('dashboards/db', json)
  File "/Library/Python/2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Library/Python/2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/Library/Python/2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Library/Python/2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/aed/shp/lib/grafana/helper.py", line 67, in api_post_with_data
    raise IOError("Error in api_post_with_data: " + function + " - " + resp.text)
IOError: Error in api_post_with_data: dashboards/db - {"message":"Failed to save dashboard"}
2019-05-23 15:21:06,219 - [create_grafana_dashboards.py:263 - create_service_dashboards() ] - ERROR - Dashboard creation error: SHS CCRS Voice Agent
Traceback (most recent call last):
  File "create_grafana_dashboards.py", line 260, in create_service_dashboards
    create_single_dashboard(dash_text, service.name, org_id, dash_uid, folder_name)
  File "create_grafana_dashboards.py", line 205, in create_single_dashboard
    resp = dashboards_for_organization.create_dashboard(str(dash_uid), json.loads(request_data))
  File "/opt/aed/shp/lib/grafana/dashboards.py", line 40, in create_dashboard
    id = self.helper.api_post_with_data('dashboards/db', json)
  File "/Library/Python/2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Library/Python/2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/Library/Python/2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Library/Python/2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/aed/shp/lib/grafana/helper.py", line 67, in api_post_with_data
    raise IOError("Error in api_post_with_data: " + function + " - " + resp.text)
IOError: Error in api_post_with_data: dashboards/db - {"message":"Failed to save dashboard"}
